SupplyApplication/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace SupplyApplication.Models
{
    public class Supplier
    {
        public Int32 Id { get; set; }
        public String Name { get; set; }
        public String SIRET { get; set; }
        public String Address { get; set; }
        public String PostalCode { get; set; }
        public String Location{ get; set; }
        public String Country { get; set; }
        public Double QualityNote { get; set; }
        public Double LogisticNote { get; set; }
        public Int32 CategoryId { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
        public virtual ICollection<Item> Items { get; set; }
    }
}

SupplyApplication/Controllers/PurchaseOrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplyApplication.Data;
using SupplyApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SupplyApplication.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PurchaseOrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PurchaseOrderController(ApplicationDbContext injectedContext)
        {
            _context = injectedContext;
        }

        [HttpGet]
        public IActionResult NewOrder(Int32 Id)
        {
            return View(GetSupplierById(Id));
        }

        [HttpPost, ActionName("NewOrder")]
        public IActionResult NewOrder([FromQuery] Int32 supplierId, [FromForm] OrderLine line)
        {
            CreateSupplierOrder(supplierId);
            return View(GetSupplierById(supplierId));
        }

        public Supplier GetSupplierById(Int32 supplierId)
        {
            IEnumerable<Supplier> suppliers = new List<Supplier>(_context.Suppliers.Select(s => s));
            Supplier supplier = suppliers.Where(s => s.Id == supplierId)
                                         .FirstOrDefault();
            return supplier;
        }
        public PurchaseOrder CreateSupplierOrder(Int32 supplierId)
        {
            Supplier supplier = GetSupplierById(supplierId);
            PurchaseOrder order = new PurchaseOrder();
            order.CreationDate = DateTime.Now;
            order.SupplierId = supplierId;
            supplier.PurchaseOrders.Add(order);
            _context.SaveChanges();

            return order;
        }

        public PurchaseOrder GetOrderById(Int32 orderId)
        {
            IEnumerable<PurchaseOrder> orders = new List<PurchaseOrder>(_context.PurchaseOrders.Select(po => po));
            PurchaseOrder order = orders.Where(po => po.Id == orderId)
                                         .FirstOrDefault();
            return order;
        }
        public OrderLine CreateSupplierOrderLine(Int32 orderId, OrderLine line)
        {
            PurchaseOrder order = GetOrderById(orderId);
            line.DeliveryDate = DateTime.Now.AddDays(line.DeliveryTime);
            line.PurchaseOrderId = order.Id;
            _context.OrderLines.Add(line);
            _context.SaveChanges();

            return line;
        }
    }
}

SupplyApplication/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplyApplication.Data;
using SupplyApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SupplyApplication.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SupplierController(ApplicationDbContext injectedContext)
        {
            _context = injectedContext;
        }

        [HttpGet]
        public IActionResult Index(String searchString)
        {
            if (_context.Suppliers.Any())
            {
                return View(GetSupplierList(searchString));
            }
            else
            {
                return BadRequest();
            }
            
        }

        [HttpGet]
        public IActionResult SupplierDetails(Int32 Id)
        {
            if (Id != 0)
            {
                return View(GetSupplierDetails(Id));
            }
            else
            {
                return BadRequest();
            }

        }
        public List<Supplier> GetSupplierList(String searchString)
        {
            List<Supplier> suppliers = new List<Supplier>(_context.Suppliers.Where(s => s.Name.Contains(searchString) || s.SIRET.Contains(searchString) || s.Location.Contains(searchString)));                                                                 
            return suppliers;
        }

        public Supplier GetSupplierDetails(Int32 supplierId)
        {
            IEnumerable<Supplier> suppliers = new List<Supplier>();
            Supplier supplier = new Supplier();
            suppliers = _context.Suppliers.Where(s => s.Id == supplierId).Include(s => s.PurchaseOrders).Include(s => s.Items);
            supplier = suppliers.FirstOrDefault();
            
            foreach (PurchaseOrder order in supplier.PurchaseOrders)
            {
                GetOrderDetails(order.Id);
                
                foreach(OrderLine line in order.OrderLines)
                {
                    GetOrderLines(order.Id);
                }
            }

            foreach(Item item in supplier.Items)
            {
                GetSupplierItems(supplier.Id);
            }

            return supplier;
        }

        public PurchaseOrder GetOrderDetails(Int32 orderId)
        {
            IEnumerable<PurchaseOrder> purchaseOrders = new List<PurchaseOrder>();
            PurchaseOrder purchaseOrder = new PurchaseOrder();
            purchaseOrders = _context.PurchaseOrders.Where(p => p.Id == orderId).Include(p => p.OrderLines) ;
            purchaseOrder = purchaseOrders.FirstOrDefault();
            return purchaseOrder;
        }
        public IEnumerable<OrderLine> GetOrderLines(Int32 orderId)
        {
            IEnumerable<OrderLine> lines = new List<OrderLine>();
            lines = _context.OrderLines.Select(i => i);
            return lines;
        }

        public IEnumerable<Item> GetSupplierItems(Int32 supplierId)
        {
            IEnumerable<Item> items = new List<Item>();
            items = _context.Items.Include(i => i.Suppliers.Where(s => s.Id ==supplierId)).Include(i => i.Suppliers);
            return items;
        }

    }
}

SupplyApplication/Views/Supplier/Index.cshtml
@model List<Supplier>

@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="d-flex justify-content-center">
        <div class="card m-3">
            <div class="card-header font-weight-bold" style="color:darkblue; text-align:left;">
                Find Supplier
            </div>
            <div class="card-body">
                <form class="form-inline" asp-controller="Supplier" asp-action="Index" method="get">
                    <input type="text" name="SearchString" class="form-control rounded m-2" placeholder="Supplier Name, SIRET">
                    <button type="submit" class="btn" style="background-color:darkblue; color:aliceblue">Search</button>
                </form>
            </div>
        </div>
    </div>

    <div class="d-flex justify-content-center">
        @if (Model.Any() == false)
        {
            <div class="alert alert-warning alert-dismissible collapse" role="alert">
                <strong>Sorry but this supplier was not found ... </strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        else
        {
            <div class="d-flex justify-content-center">
                <table class="table table-responsive table-hover">
                    <thead style="background-color:darkblue; color:aliceblue; text-align:center">
                        <tr>
                            <th scope="col">SIRET</th>
                            <th scope="col">Denomination</th>
                            <th scope="col">Address</th>
                            <th scope="col">Country</th>
                            <th scope="col"> ... </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Supplier supplier in Model)
                        {
                            <tr>
                                <th scope="row">@supplier.SIRET</th>
                                <td>@supplier.Name</td>
                                <td>@supplier.Address, @supplier.PostalCode, @supplier.Location</td>
                                <td>@supplier.Country</td>
                                <td>
                                    <a class="btn " style="background-color:darkblue; color:aliceblue" asp-area="" asp-controller="Supplier" asp-action="SupplierDetails" asp-route-Id="@supplier.Id"> Details </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

SupplyApplication/Views/Supplier/SupplierDetails.cshtml
@model Supplier
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <div class="card m-2">
                <div class="card-header" style="background-color:darkblue">
                    <h5 class="pt-2 pb-2" style="color:aliceblue">@Model.Name</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><h6 class="pt-2 pb-2" style="color:darkblue">SIRET Number :</h6> @Model.SIRET </li>
                    <li class="list-group-item"><h6 class="pt-2 pb-2" style="color:darkblue"> Main Address :</h6> @Model.Address, @Model.PostalCode, @Model.Location, @Model.Country  </li>
                </ul>
            </div>
            <div class="card m-2">
                <div class="card-header" style="background-color:aliceblue">
                    <h5 class="pt-2 pb-2" style="color:darkblue">Scoring</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item text-center">
                        <h6 class="pt-2 pb-2" style="color:darkblue">Quality Note :</h6>
                        @if (Model.QualityNote >= 8)
                        {
                            <h6 class="pt-2 pb-2" style="color:green"> @Model.QualityNote / 10 </h6>
                        }
                        @if (Model.QualityNote < 8)
                        {
                            <h6 class="pt-2 pb-2" style="color:orange"> @Model.QualityNote / 10 </h6>
                        }
                        @if (Model.QualityNote < 6)
                        {
                            <h6 class="pt-2 pb-2" style="color:red">@Model.QualityNote / 10 </h6>
                        }
                    </li>
                    <li class="list-group-item text-center">
                        <h6 class="pt-2 pb-2" style="color:darkblue"> Logistic Note :</h6> @if (Model.LogisticNote >= 8)
                        {
                            <h6 class="pt-2 pb-2" style="color:green">@Model.LogisticNote / 10 </h6>
                        }
                        @if (Model.LogisticNote < 8)
                        {
                            <h6 class="pt-2 pb-2" style="color:orange">@Model.LogisticNote / 10 </h6>
                        }
                        @if (Model.LogisticNote < 6)
                        {
                            <h6 class="pt-2 pb-2" style="color:red">@Model.LogisticNote / 10 </h6>
                        }
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="card m-2">
                <div class="card-header align-items-center" style="background-color:aliceblue">
                    <div class="d-flex justify-content-between">
                        <div>
                            <h5 class="pt-2 pb-2" style="color:darkblue">Purchase Orders </h5>
                        </div>
                        <div>
                            <a class="btn" style="background-color:darkblue; color:aliceblue" asp-controller="PurchaseOrder" asp-action="NewOrder" asp-route-Id="@Model.Id" >New Order</a>
                        </div>
                    </div>
                </div>
                    <div class="card-body text-justify">
                        @foreach (PurchaseOrder po in Model.PurchaseOrders)
                        {
                            <div>
                                <table class="table table-hover">
                                    <thead style="background-color:darkblue; color:aliceblue; text-align:center">
                                        <tr>
                                            <th scope="col">Order Ref.</th>
                                            <th scope="col">Date</th>
                                            <th scope="col">Lines</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row">@po.Id</th>
                                            <td>@po.CreationDate</td>
                                            <td><a class="btn" data-toggle="modal" data-target="#toggle-modal-@po.Id" style="background-color:darkblue; color:aliceblue">Details</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div>
                                <div class="modal fade bd-example-modal-lg pre-scrollable" id="toggle-modal-@po.Id" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="p-2">
                                                <h5 class="pt-2 pb-2" style="color:darkblue; text-align:right"> Purchase Order #@po.Id </h5>
                                                <table class="table table-hover">
                                                    <thead style="background-color:darkblue; color:aliceblue; text-align:center">
                                                        <tr>
                                                            <th scope="col">Item Ref.</th>
                                                            <th scope="col">Item Name</th>
                                                            <th scope="col">Quantity</th>
                                                            <th scope="col">Unit Price</th>
                                                            <th scope="col">Discount</th>
                                                            <th scope="col">Delivery Date</th>
                                                            <th scope="col">Amount</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (OrderLine line in po.OrderLines)
                                                        {
                                                            <tr style="color:darkblue;">
                                                                <th scope="row">@line.ItemReference</th>
                                                                <td>@line.ItemName</td>
                                                                <td>@line.Quantity</td>
                                                                <td>@line.UnitPrice</td>
                                                                <td>@line.Remise</td>
                                                                <td>@line.DeliveryDate</td>
                                                                <td>@line.Amount €</td>
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
        </div>
    </div>
</div>
             